# Generated by Django 5.0.4 on 2024-04-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_details', models.TextField(max_length=10)),
                ('address', models.TextField(max_length=400)),
                ('vendor_code', models.CharField(max_length=200)),
                ('on_time_delivery_rate', models.FloatField(max_length=50)),
                ('quality_rating_avg', models.FloatField(max_length=50)),
                ('average_response_time', models.FloatField(max_length=50)),
                ('fulfillment_rate', models.FloatField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='purchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50)),
                ('order_date', models.DateTimeField(max_length=10)),
                ('delivery_date', models.DateTimeField(max_length=10)),
                ('items', models.JSONField(max_length=200)),
                ('quantity', models.IntegerField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('quality_rating', models.FloatField(max_length=100)),
                ('issue_date', models.DateTimeField(max_length=10)),
                ('acknowledgment_date', models.DateTimeField(max_length=10)),
                ('vendor', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='vendorsite.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='historicalPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=20)),
                ('on_time_delivery_rate', models.FloatField(max_length=50)),
                ('quality_rating_avg', models.FloatField(max_length=50)),
                ('average_response_time', models.FloatField(max_length=50)),
                ('fulfilment_rate', models.FloatField(max_length=10)),
                ('vendor', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='vendorsite.vendor')),
            ],
        ),
    ]
